language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y check
  - export CFLAGS="-coverage -O0"
  - export LDFLAGS="-coverage"

install:
  - make

script:
  - make check
  - rm src/main*.c # hack to exclude from gcov
  - gcov -o src src/*.c
  - gcov -o lib lib/strntod.c lib/strntoimax.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
